// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Debug logging
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('❌ Supabase Configuration Error:');
  console.error('VITE_SUPABASE_URL:', SUPABASE_URL || 'NOT SET');
  console.error('VITE_SUPABASE_ANON_KEY:', SUPABASE_PUBLISHABLE_KEY ? 'SET' : 'NOT SET');
  
  if (import.meta.env.DEV) {
    console.error('🔧 Fix: Create .env.local with your Supabase credentials');
    console.error('📋 Copy from .env.example');
    console.error('🌐 Check your Supabase project is active');
  }
} else {
  console.log('✅ Supabase configured successfully');
  console.log('🌐 Supabase URL:', SUPABASE_URL);
}

// Test Supabase connection
export const testSupabaseConnection = async () => {
  try {
    const { data, error } = await supabase.from('profiles').select('count').limit(1);
    if (error) {
      console.error('❌ Supabase Connection Test Failed:', error);
      return false;
    }
    console.log('✅ Supabase Connection Test Passed');
    return true;
  } catch (err) {
    console.error('❌ Supabase Network Error:', err);
    return false;
  }
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});